export const governmentUniversities = [
  {
    id: 1,
    name: "IISc Bangalore",
    fullName: "Indian Institute of Science",
    type: "Central Institute",
    location: "Bengaluru, Karnataka",
    nirf: 1,
    naac: "A++",
    established: 1909,
    website: "https://iisc.ac.in",
    applyLink: "https://iisc.ac.in/admissions",
    entranceExam: "KVPY / JEE / NEET / GATE",
    logo: "IISc",
    color: "#1a3a5c",
    fees: { ug: "~₹30,000/yr", pg: "~₹15,000/yr" },
    courses: {
      bsc: ["B.Sc Research (Physics)", "B.Sc Research (Chemistry)", "B.Sc Research (Biology)", "B.Sc Research (Maths)", "B.Sc Research (Materials)"],
      msc: ["M.Sc (Science)"],
      mtech: ["M.Tech (various streams)"],
      phd: ["PhD in all science & engineering streams"],
    },
    admission: [
      "B.Sc Research: KVPY / JEE Advanced / NEET",
      "M.Tech: GATE score required",
      "PhD: Written test + Interview",
      "Apply at iisc.ac.in",
    ],
    highlights: ["#1 Research Institute India", "Nobel-level faculty", "400+ acre campus", "Govt fully funded"],
    knownFor: "Pure Science & Research",
    avgFees: "Very Low (Govt funded)",
    careerScope: ["Scientist", "Researcher", "Professor", "DRDO/ISRO/BARC"],
  },
  {
    id: 2,
    name: "JNU Delhi",
    fullName: "Jawaharlal Nehru University",
    type: "Central University",
    location: "New Delhi, Delhi",
    nirf: 2,
    naac: "A++",
    established: 1969,
    website: "https://www.jnu.ac.in",
    applyLink: "https://jnuee.jnu.ac.in",
    entranceExam: "CUET UG / CUET PG",
    logo: "JNU",
    color: "#6b1a1a",
    fees: { ug: "~₹400/yr", pg: "~₹4,000/yr" },
    courses: {
      ba: ["BA (Hons) Foreign Languages", "BA (Hons) Social Sciences"],
      bsc: ["B.Sc-M.Sc Integrated (5yr)"],
      ma: ["MA Political Science", "MA History", "MA Economics", "MA International Relations", "MA Sociology", "MA Sanskrit", "MA Hindi", "MA English"],
      msc: ["M.Sc Life Sciences", "M.Sc Biotechnology", "M.Sc Environmental Sciences"],
      mtech: ["M.Tech Computer Science"],
      phd: ["PhD in all streams"],
    },
    admission: [
      "UG: CUET UG score",
      "PG: CUET PG score",
      "One of lowest fees in India",
      "Highly competitive cutoffs",
    ],
    highlights: ["Lowest fees in India", "Top social sciences", "Research culture", "Vibrant campus life"],
    knownFor: "Social Sciences, Languages & Research",
    avgFees: "Extremely Low (₹400/yr UG)",
    careerScope: ["IAS/IFS Officer", "Professor", "Journalist", "Diplomat", "Researcher"],
  },
  {
    id: 3,
    name: "BHU Varanasi",
    fullName: "Banaras Hindu University",
    type: "Central University",
    location: "Varanasi, Uttar Pradesh",
    nirf: 6,
    naac: "A+",
    established: 1916,
    website: "https://www.bhu.ac.in",
    applyLink: "https://bhuonline.in",
    entranceExam: "CUET UG / CUET PG",
    logo: "BHU",
    color: "#7a4a00",
    fees: { ug: "~₹2,000/yr", pg: "~₹5,000/yr" },
    courses: {
      ba: ["BA (Hons) Economics", "BA (Hons) History", "BA (Hons) Political Science", "BA (Hons) Sociology", "BA (Hons) Philosophy", "BA (Hons) Sanskrit"],
      bsc: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths", "B.Sc Biology", "B.Sc Agriculture"],
      btech: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mechanical", "B.Tech Civil", "B.Tech Mining"],
      bcom: ["B.Com (Hons)"],
      ma: ["MA in 30+ subjects"],
      msc: ["M.Sc Physics", "M.Sc Chemistry", "M.Sc Maths"],
      mtech: ["M.Tech 10+ streams"],
      mbbs: ["MBBS at IMS-BHU"],
    },
    admission: [
      "UG: CUET UG mandatory",
      "B.Tech: JEE Main score",
      "MBBS: NEET score",
      "1300+ acre campus",
    ],
    highlights: ["1300+ acre campus", "MBBS + BTech + BA all in one", "Heritage university", "60,000+ students"],
    knownFor: "Largest Residential University in Asia",
    avgFees: "Very Low (Govt funded)",
    careerScope: ["Engineering", "Medicine", "Civil Services", "Academia", "Research"],
  },
  {
    id: 4,
    name: "Delhi University",
    fullName: "University of Delhi",
    type: "Central University",
    location: "New Delhi, Delhi",
    nirf: 5,
    naac: "A++",
    established: 1922,
    website: "https://www.du.ac.in",
    applyLink: "https://admission.uod.ac.in",
    entranceExam: "CUET UG",
    logo: "DU",
    color: "#1a3d1a",
    fees: { ug: "~₹10,000–15,000/yr", pg: "~₹8,000–12,000/yr" },
    courses: {
      ba: ["BA (Hons) Economics", "BA (Hons) English", "BA (Hons) History", "BA (Hons) Political Science", "BA (Hons) Psychology", "BA (Hons) Sociology", "BA (Hons) Philosophy"],
      bsc: ["B.Sc (H) Physics", "B.Sc (H) Chemistry", "B.Sc (H) Maths", "B.Sc (H) Statistics", "B.Sc (H) Computer Science"],
      bcom: ["B.Com (Hons)", "B.Com"],
      bba: ["BBA (FIA)"],
      ma: ["MA Economics", "MA English", "MA History", "MA Political Science"],
      msc: ["M.Sc Physics", "M.Sc Chemistry", "M.Sc Maths"],
      llb: ["LLB (3-year)", "BA LLB (5-year at Campus Law Centre)"],
    },
    admission: [
      "UG: CUET UG mandatory (from 2022)",
      "PG: CUET PG score",
      "90+ colleges under DU",
      "Highest competition in India",
    ],
    highlights: ["90+ colleges", "SRCC, LSR, Hindu, St Stephens", "Best BA/BCom in India", "Top placement network"],
    knownFor: "BA (Hons) Economics at SRCC, BCom at SRCC",
    avgFees: "Low-Moderate",
    careerScope: ["Finance", "Civil Services", "Law", "Journalism", "Academia", "Corporate"],
  },
  {
    id: 5,
    name: "Jamia Millia Islamia",
    fullName: "Jamia Millia Islamia",
    type: "Central University",
    location: "New Delhi, Delhi",
    nirf: 4,
    naac: "A++",
    established: 1920,
    website: "https://www.jmi.ac.in",
    applyLink: "https://jmiadmission.ac.in",
    entranceExam: "CUET UG / JMI Entrance",
    logo: "JMI",
    color: "#2c5f2e",
    fees: { ug: "~₹8,000/yr", pg: "~₹10,000/yr" },
    courses: {
      ba: ["BA (Hons) Mass Media", "BA (Hons) Arabic", "BA (Hons) English", "BA (Hons) History", "BA (Hons) Urdu"],
      bsc: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths"],
      btech: ["B.Tech CSE", "B.Tech ECE", "B.Tech Civil"],
      bba: ["BBA"],
      ma: ["MA Mass Comm", "MA English", "MA Arabic", "MA Education"],
      mtech: ["M.Tech CSE", "M.Tech ECE"],
      barch: ["B.Arch"],
    },
    admission: [
      "UG: CUET UG score",
      "Some courses: JMI own entrance",
      "B.Tech: JEE Main accepted",
      "NIRF #4 university",
    ],
    highlights: ["Mass Comm is top-rated", "B.Arch very popular", "Govt funded", "Research excellence"],
    knownFor: "Mass Communication & Media Studies",
    avgFees: "Very Low",
    careerScope: ["Journalism", "Media", "Engineering", "Civil Services", "Education"],
  },
  {
    id: 6,
    name: "Jadavpur University",
    fullName: "Jadavpur University",
    type: "State University (West Bengal)",
    location: "Kolkata, West Bengal",
    nirf: 9,
    naac: "A",
    established: 1955,
    website: "https://jadavpuruniversity.in",
    applyLink: "https://jadavpuruniversity.in/admission",
    entranceExam: "WBJEE / JEE Main / JUEE",
    logo: "JU",
    color: "#1a4a6b",
    fees: { ug: "~₹5,000/yr", pg: "~₹6,000/yr" },
    courses: {
      btech: ["B.Tech CSE", "B.Tech ECE", "B.Tech Electrical", "B.Tech Mechanical", "B.Tech Chemical", "B.Tech Civil"],
      bsc: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths"],
      ba: ["BA English", "BA Bengali", "BA Comparative Literature", "BA History", "BA Philosophy"],
      mtech: ["M.Tech 15+ streams"],
      ma: ["MA English", "MA Comparative Lit", "MA Film Studies"],
      msc: ["M.Sc Physics", "M.Sc Chemistry", "M.Sc Maths"],
    },
    admission: [
      "B.Tech: WBJEE or JEE Main",
      "BA/BSc: JUEE (own entrance)",
      "Highly competitive",
      "Best engineering in East India",
    ],
    highlights: ["Top engineering in East India", "Comparative Literature is iconic", "Research focused", "State funded"],
    knownFor: "Engineering + Arts — both top class",
    avgFees: "Very Low",
    careerScope: ["Software engineer", "Core engineering", "Literature/Arts", "Research", "Civil services"],
  },
  {
    id: 7,
    name: "AMU Aligarh",
    fullName: "Aligarh Muslim University",
    type: "Central University",
    location: "Aligarh, Uttar Pradesh",
    nirf: 10,
    naac: "A+",
    established: 1875,
    website: "https://www.amu.ac.in",
    applyLink: "https://amucontrollerexams.com",
    entranceExam: "CUET UG / AMU Entrance",
    logo: "AMU",
    color: "#5a1a5a",
    fees: { ug: "~₹3,000/yr", pg: "~₹5,000/yr" },
    courses: {
      ba: ["BA (Hons) History", "BA (Hons) English", "BA (Hons) Urdu", "BA (Hons) Arabic", "BA (Hons) Persian", "BA (Hons) Economics"],
      bsc: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths", "B.Sc Agriculture"],
      btech: ["B.Tech CSE", "B.Tech Mechanical", "B.Tech ECE", "B.Tech Civil"],
      mbbs: ["MBBS at JNMC"],
      bba: ["BBA"],
      ma: ["MA in 20+ subjects"],
      mtech: ["M.Tech multiple streams"],
      llb: ["LLB (3yr)", "BA LLB (5yr)"],
    },
    admission: [
      "UG: CUET UG / AMU own entrance",
      "MBBS: NEET required",
      "B.Tech: JEE Main accepted",
      "Historic 1875-founded institution",
    ],
    highlights: ["Heritage 150yr old", "MBBS + BTech + BA", "Minority institution", "Rich alumni network"],
    knownFor: "One of oldest universities in India",
    avgFees: "Very Low",
    careerScope: ["Medicine", "Engineering", "Law", "Civil Services", "Diplomacy"],
  },
  {
    id: 8,
    name: "University of Hyderabad",
    fullName: "University of Hyderabad (HCU)",
    type: "Central University",
    location: "Hyderabad, Telangana",
    nirf: 10,
    naac: "A+",
    established: 1974,
    website: "https://uohyd.ac.in",
    applyLink: "https://admissions.uohyd.ac.in",
    entranceExam: "CUET PG / UoH Entrance",
    logo: "HCU",
    color: "#1a5a3a",
    fees: { ug: "~₹5,000/yr", pg: "~₹8,000/yr" },
    courses: {
      bsc: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths", "B.Sc Life Sciences"],
      ba: ["BA (Hons) English", "BA (Hons) Telugu", "BA (Hons) Hindi"],
      ma: ["MA English", "MA Telugu", "MA Hindi", "MA Political Science", "MA Sociology"],
      msc: ["M.Sc Physics", "M.Sc Chemistry", "M.Sc Maths", "M.Sc Biotechnology", "M.Sc Computer Science"],
      mtech: ["M.Tech CSE", "M.Tech Information Security"],
      phd: ["PhD in 50+ subjects"],
    },
    admission: [
      "UG: CUET UG score",
      "PG: CUET PG or UoH entrance",
      "PhD: Written test + Interview",
      "Best for PG & Research",
    ],
    highlights: ["Best for PG in South India", "Research hub", "500+ acre campus", "Govt funded"],
    knownFor: "Postgraduate Studies & Research",
    avgFees: "Very Low",
    careerScope: ["Researcher", "Scientist", "Professor", "Civil Services", "IT sector"],
  },
  {
    id: 9,
    name: "Visva Bharati",
    fullName: "Visva-Bharati University (Tagore's University)",
    type: "Central University",
    location: "Shantiniketan, West Bengal",
    nirf: 19,
    naac: "A",
    established: 1921,
    website: "https://visvabharati.ac.in",
    applyLink: "https://visvabharati.ac.in/Admission.html",
    entranceExam: "CUET UG / VBU Entrance",
    logo: "VBU",
    color: "#7a5a00",
    fees: { ug: "~₹3,000/yr", pg: "~₹5,000/yr" },
    courses: {
      ba: ["BA Fine Arts", "BA Music", "BA Dance", "BA Bengali", "BA Sanskrit", "BA History", "BA Economics"],
      bsc: ["B.Sc Agriculture", "B.Sc Maths", "B.Sc Physics"],
      bfa: ["BFA Painting", "BFA Sculpture", "BFA Graphic Art"],
      ma: ["MA Bengali", "MA Sanskrit", "MA English", "MA Music", "MA Dance"],
      msc: ["M.Sc Agriculture"],
    },
    admission: [
      "UG: CUET UG score",
      "Fine Arts: Talent/portfolio test",
      "Founded by Rabindranath Tagore",
      "Unique open-air learning",
    ],
    highlights: ["Founded by Tagore", "Unique open-air classrooms", "Best Fine Arts in India", "UNESCO heritage campus"],
    knownFor: "Fine Arts, Music, Dance & Humanities",
    avgFees: "Very Low",
    careerScope: ["Artist", "Musician", "Dancer", "Cultural diplomat", "Academic"],
  },
  {
    id: 10,
    name: "Pondicherry University",
    fullName: "Pondicherry University",
    type: "Central University",
    location: "Puducherry",
    nirf: 25,
    naac: "A+",
    established: 1985,
    website: "https://www.pondiuni.edu.in",
    applyLink: "https://www.pondiuni.edu.in/admission",
    entranceExam: "CUET UG / CUET PG",
    logo: "PU",
    color: "#1a5a5a",
    fees: { ug: "~₹5,000/yr", pg: "~₹8,000/yr" },
    courses: {
      ba: ["BA Tamil", "BA French", "BA English", "BA Sociology", "BA History"],
      bsc: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc CS", "B.Sc Maths"],
      btech: ["B.Tech CSE", "B.Tech ECE", "B.Tech IT"],
      bba: ["BBA", "BCA"],
      ma: ["MA French", "MA Tamil", "MA English", "MA Economics"],
      msc: ["M.Sc all streams"],
      mtech: ["M.Tech CSE", "M.Tech ECE"],
    },
    admission: [
      "UG: CUET UG",
      "PG: CUET PG",
      "French language advantage",
      "Beach campus — unique experience",
    ],
    highlights: ["Beach campus", "French language advantage", "Central university benefits", "South India hub"],
    knownFor: "French Language Studies & Beach Campus",
    avgFees: "Very Low",
    careerScope: ["French translator", "Software engineer", "Civil Services", "Banking", "Research"],
  },
  {
    id: 11,
    name: "Tezpur University",
    fullName: "Tezpur University",
    type: "Central University",
    location: "Tezpur, Assam",
    nirf: 30,
    naac: "A",
    established: 1994,
    website: "https://www.tezu.ernet.in",
    applyLink: "https://www.tezu.ernet.in/admission.html",
    entranceExam: "CUET UG / TUEE",
    logo: "TU",
    color: "#3a1a6b",
    fees: { ug: "~₹5,000/yr", pg: "~₹7,000/yr" },
    courses: {
      btech: ["B.Tech CSE", "B.Tech ECE", "B.Tech Chemical", "B.Tech Food Engineering"],
      bsc: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths"],
      ba: ["BA Mass Communication", "BA English", "BA Cultural Studies"],
      mtech: ["M.Tech CSE", "M.Tech ECE", "M.Tech Signal Processing"],
      msc: ["M.Sc all streams"],
      ma: ["MA Mass Comm", "MA Cultural Studies"],
    },
    admission: [
      "B.Tech: JEE Main / TUEE",
      "BA/BSc: CUET UG",
      "Best central university in Northeast India",
      "Research-focused",
    ],
    highlights: ["Best in Northeast India", "Research excellence", "Nature campus", "Central univ benefits"],
    knownFor: "Northeast India's Premier Central University",
    avgFees: "Very Low",
    careerScope: ["Software engineer", "Core engineering", "Media", "Civil Services", "Research"],
  },
  {
    id: 12,
    name: "Central Univ Punjab",
    fullName: "Central University of Punjab",
    type: "Central University",
    location: "Bathinda, Punjab",
    nirf: 33,
    naac: "A",
    established: 2009,
    website: "https://cup.edu.in",
    applyLink: "https://cup.edu.in/admission",
    entranceExam: "CUET UG / CUET PG",
    logo: "CUP",
    color: "#0a3d62",
    fees: { ug: "~₹8,000/yr", pg: "~₹10,000/yr" },
    courses: {
      ba: ["BA (Hons) Economics", "BA (Hons) English", "BA (Hons) Punjabi", "BA Social Work"],
      bsc: ["B.Sc Environmental Sciences", "B.Sc Maths", "B.Sc Chemistry"],
      btech: ["B.Tech CSE", "B.Tech Bioinformatics"],
      ma: ["MA Economics", "MA English", "MA Education", "MA Sociology"],
      msc: ["M.Sc Environmental Sciences", "M.Sc Bioinformatics", "M.Sc Chemistry"],
      mtech: ["M.Tech CSE"],
      phd: ["PhD multiple streams"],
    },
    admission: [
      "UG/PG: CUET UG/PG mandatory",
      "Modern central university",
      "Growing research output",
      "Affordable central univ",
    ],
    highlights: ["Modern campus", "Research growing", "Affordable central univ", "Punjab region advantage"],
    knownFor: "Environmental Sciences & Bioinformatics",
    avgFees: "Very Low",
    careerScope: ["Environment sector", "IT", "Civil Services", "Research", "Teaching"],
  },
];

export const types = ["All", "Central University", "Central Institute", "State University (West Bengal)"];
export const courseFilters = ["All", "BTech", "BA/BSc/BCom", "MBBS", "MA/MSc", "PhD"];
