export const privateUniversities = [
  {
    id: 1,
    name: "VIT Vellore",
    fullName: "Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    nirf: 11,
    naac: "A++",
    established: 1984,
    website: "https://vit.ac.in",
    applyLink: "https://applications.vit.ac.in",
    entranceExam: "VITEEE",
    logo: "VIT",
    color: "#1a6b3c",
    fees: { btech: "1.98 – 3.98 L/yr", mtech: "1.5 – 2.5 L/yr" },
    avgPackage: "₹8.5 LPA",
    highestPackage: "₹1.05 Cr",
    courses: {
      btech: ["CSE", "AI & ML", "ECE", "Mechanical", "Civil", "IT", "Data Science", "Robotics"],
      mtech: ["CSE", "VLSI", "Embedded Systems", "CAD/CAM"],
      ba: ["Economics", "English", "Sociology"],
      ma: ["Economics", "English Literature"],
      pg: ["MBA", "MCA", "MSc"],
    },
    admission: [
      "Appear in VITEEE (April)",
      "Register at vit.ac.in (₹1,350 fee)",
      "Merit-based counselling",
      "Min 60% in PCM in Class 12",
    ],
    highlights: ["6000+ BTech seats", "Global tie-ups", "Green campus", "Research labs"],
    topRecruiters: ["Microsoft", "Google", "Amazon", "Wipro", "TCS"],
  },
  {
    id: 2,
    name: "BITS Pilani",
    fullName: "Birla Institute of Technology & Science",
    location: "Pilani, Rajasthan",
    nirf: 16,
    naac: "A",
    established: 1964,
    website: "https://www.bits-pilani.ac.in",
    applyLink: "https://www.bitsadmission.com",
    entranceExam: "BITSAT",
    logo: "BITS",
    color: "#8B1A1A",
    fees: { btech: "20 – 22 L/yr", mtech: "10 – 14 L/yr" },
    avgPackage: "₹18 LPA",
    highestPackage: "₹1.2 Cr",
    courses: {
      btech: ["CSE", "ECE", "Mechanical", "Chemical", "Civil", "EEE"],
      mtech: ["CSE", "Embedded Systems", "Microelectronics"],
      ba: [],
      ma: [],
      pg: ["MBA", "MSc Physics", "MSc Chemistry", "MSc Maths"],
    },
    admission: [
      "Appear in BITSAT (May)",
      "Apply at bitsadmission.com",
      "No JEE Main accepted",
      "Merit-only, no reservations",
    ],
    highlights: ["No-reservation policy", "WILP programs", "Strong alumni", "Startup culture"],
    topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "Qualcomm", "Samsung"],
  },
  {
    id: 3,
    name: "SRM University",
    fullName: "SRM Institute of Science & Technology",
    location: "Kattankulathur, Chennai",
    nirf: 20,
    naac: "A++",
    established: 1985,
    website: "https://www.srmist.edu.in",
    applyLink: "https://www.srmist.edu.in/admissions",
    entranceExam: "SRMJEEE",
    logo: "SRM",
    color: "#003087",
    fees: { btech: "2.50 – 4.00 L/yr", mtech: "1.5 – 2.5 L/yr" },
    avgPackage: "₹7.5 LPA",
    highestPackage: "₹45 LPA",
    courses: {
      btech: ["CSE", "AI & Data Science", "ECE", "Mechanical", "Civil", "Biotech"],
      mtech: ["CSE", "ECE", "Mechanical"],
      ba: ["English", "History", "Economics"],
      ma: ["English", "History"],
      pg: ["MBA", "MCA", "MSc"],
    },
    admission: [
      "Appear in SRMJEEE",
      "Apply at srmist.edu.in",
      "JEE Main also accepted",
      "7000+ seats at KTR campus",
    ],
    highlights: ["7000+ seats", "Multiple campuses", "Modern infra", "Strong placements"],
    topRecruiters: ["TCS", "HCL", "Deloitte", "Wipro", "Infosys"],
  },
  {
    id: 4,
    name: "Manipal University",
    fullName: "Manipal Institute of Technology",
    location: "Manipal, Karnataka",
    nirf: 9,
    naac: "A++",
    established: 1957,
    website: "https://manipal.edu/mit",
    applyLink: "https://manipal.edu/mu/admissions",
    entranceExam: "MET / JEE Main",
    logo: "MIT",
    color: "#C8102E",
    fees: { btech: "3.0 – 5.0 L/yr", mtech: "2.0 – 3.0 L/yr" },
    avgPackage: "₹9 LPA",
    highestPackage: "₹60 LPA",
    courses: {
      btech: ["CSE", "IT", "ECE", "Mechanical", "Aerospace", "Chemical"],
      mtech: ["CSE", "ECE", "Structural Engg"],
      ba: ["Journalism", "Psychology", "English"],
      ma: ["English", "Sociology"],
      pg: ["MBA", "MCA", "MSc Biotechnology"],
    },
    admission: [
      "Apply via MET or JEE Main",
      "Register at manipal.edu",
      "Min 50% in PCM",
      "Online counselling after exam",
    ],
    highlights: ["Medical + Engg campus", "Global university", "Research focus", "Island campus"],
    topRecruiters: ["Amazon", "Flipkart", "Honeywell", "L&T", "Bosch"],
  },
  {
    id: 5,
    name: "Amity University",
    fullName: "Amity University Noida",
    location: "Noida, Uttar Pradesh",
    nirf: 35,
    naac: "A+",
    established: 2005,
    website: "https://www.amity.edu",
    applyLink: "https://www.amity.edu/admissions",
    entranceExam: "AEEE / JEE Main",
    logo: "AU",
    color: "#7B0D1E",
    fees: { btech: "3.13 – 4.5 L/yr", mtech: "2.0 – 3.5 L/yr" },
    avgPackage: "₹6.3 LPA",
    highestPackage: "₹25 LPA",
    courses: {
      btech: ["CSE", "IT", "ECE", "Mechanical", "Civil", "Bioinformatics"],
      mtech: ["CSE", "ECE", "Biotechnology"],
      ba: ["Economics", "Psychology", "Journalism", "English", "Political Science"],
      ma: ["Economics", "English", "Psychology", "Public Policy"],
      pg: ["MBA", "MCA", "MSc", "LLM", "MPH"],
    },
    admission: [
      "Apply at amity.edu",
      "AEEE or JEE Main accepted",
      "300+ courses offered",
      "International campuses too",
    ],
    highlights: ["300+ courses", "International campus", "Corporate tie-ups", "Large alumni network"],
    topRecruiters: ["TCS", "Wipro", "Cognizant", "IBM", "EY"],
  },
  {
    id: 6,
    name: "Thapar University",
    fullName: "Thapar Institute of Engineering & Technology",
    location: "Patiala, Punjab",
    nirf: 28,
    naac: "A",
    established: 1956,
    website: "https://www.thapar.edu",
    applyLink: "https://www.thapar.edu/admissions",
    entranceExam: "JEE Main",
    logo: "TIET",
    color: "#004B87",
    fees: { btech: "2.5 – 3.5 L/yr", mtech: "1.8 – 2.5 L/yr" },
    avgPackage: "₹10 LPA",
    highestPackage: "₹50 LPA",
    courses: {
      btech: ["CSE", "ECE", "Mechanical", "Chemical", "Civil", "Electrical"],
      mtech: ["CSE", "ECE", "Thermal Engg", "Power Systems"],
      ba: [],
      ma: [],
      pg: ["MBA", "MSc Physics", "MSc Chemistry", "MSc Maths"],
    },
    admission: [
      "JEE Main score required",
      "Apply at thapar.edu",
      "Min 60% in PCM",
      "Counselling via JoSAA / institute",
    ],
    highlights: ["Research-first approach", "Strong CSE", "Industry projects", "Small batch size"],
    topRecruiters: ["Microsoft", "Oracle", "Samsung", "Schlumberger", "DRDO"],
  },
  {
    id: 7,
    name: "Chandigarh University",
    fullName: "Chandigarh University",
    location: "Mohali, Punjab",
    nirf: 22,
    naac: "A+",
    established: 2012,
    website: "https://www.cuchd.in",
    applyLink: "https://www.cuchd.in/admissions",
    entranceExam: "CUCET / JEE Main",
    logo: "CU",
    color: "#F47920",
    fees: { btech: "1.8 – 3.0 L/yr", mtech: "1.5 – 2.0 L/yr" },
    avgPackage: "₹8 LPA",
    highestPackage: "₹54 LPA",
    courses: {
      btech: ["CSE", "IT", "ECE", "Mechanical", "Civil", "AI & ML"],
      mtech: ["CSE", "ECE", "Mechanical"],
      ba: ["English", "Economics", "Journalism"],
      ma: ["English", "Economics", "Public Administration"],
      pg: ["MBA", "MCA", "MSc", "LLM"],
    },
    admission: [
      "CUCET or JEE Main accepted",
      "Apply at cuchd.in",
      "Affordable fees",
      "Startup-friendly campus",
    ],
    highlights: ["Fastest growing", "Global tie-ups", "Startup ecosystem", "Affordable"],
    topRecruiters: ["Cognizant", "Capgemini", "Amazon", "Microsoft", "Infosys"],
  },
  {
    id: 8,
    name: "KIIT University",
    fullName: "Kalinga Institute of Industrial Technology",
    location: "Bhubaneswar, Odisha",
    nirf: 17,
    naac: "A+",
    established: 1992,
    website: "https://kiit.ac.in",
    applyLink: "https://kiit.ac.in/admissions",
    entranceExam: "KIITEE",
    logo: "KIIT",
    color: "#0047AB",
    fees: { btech: "3.5 – 4.5 L/yr", mtech: "2.0 – 3.0 L/yr" },
    avgPackage: "₹7 LPA",
    highestPackage: "₹42 LPA",
    courses: {
      btech: ["CSE", "IT", "ECE", "Mechanical", "Civil", "Electrical"],
      mtech: ["CSE", "ECE", "Thermal"],
      ba: ["Economics", "English", "Political Science"],
      ma: ["Economics", "English"],
      pg: ["MBA", "MCA", "MSc"],
    },
    admission: [
      "Appear in KIITEE",
      "Apply at kiit.ac.in",
      "Min 60% in PCM",
      "Large campus life",
    ],
    highlights: ["Large campus", "Alumni network", "Balanced curriculum", "Eastern India hub"],
    topRecruiters: ["TCS", "HCL", "Tech Mahindra", "Wipro", "Mindtree"],
  },
  {
    id: 9,
    name: "Amrita University",
    fullName: "Amrita Vishwa Vidyapeetham",
    location: "Coimbatore, Tamil Nadu",
    nirf: 23,
    naac: "A++",
    established: 1994,
    website: "https://www.amrita.edu",
    applyLink: "https://www.amrita.edu/admissions",
    entranceExam: "AEEE",
    logo: "AVV",
    color: "#FF6600",
    fees: { btech: "2.0 – 4.0 L/yr", mtech: "1.5 – 2.5 L/yr" },
    avgPackage: "₹7.2 LPA",
    highestPackage: "₹56 LPA",
    courses: {
      btech: ["CSE", "ECE", "Mechanical", "Chemical", "Civil", "AI & Robotics"],
      mtech: ["CSE", "VLSI", "Embedded Systems"],
      ba: ["Economics", "English"],
      ma: ["Economics"],
      pg: ["MBA", "MCA", "MSc Bioinformatics"],
    },
    admission: [
      "Appear in AEEE",
      "Apply at amrita.edu",
      "Value-based education",
      "NAAC A++ accredited",
    ],
    highlights: ["Research-oriented", "Global internships", "NAAC A++", "Multiple campuses"],
    topRecruiters: ["Intel", "Accenture", "Microsoft", "Amazon", "Bosch"],
  },
  {
    id: 10,
    name: "Shiv Nadar University",
    fullName: "Shiv Nadar University",
    location: "Greater Noida, UP",
    nirf: 38,
    naac: "A+",
    established: 2011,
    website: "https://snu.edu.in",
    applyLink: "https://admissions.snu.edu.in",
    entranceExam: "SNUSAT / JEE Main",
    logo: "SNU",
    color: "#003153",
    fees: { btech: "3.5 – 5.0 L/yr", mtech: "2.0 – 3.5 L/yr" },
    avgPackage: "₹12 LPA",
    highestPackage: "₹65 LPA",
    courses: {
      btech: ["CSE", "ECE", "Mechanical", "Civil", "Chemical"],
      mtech: ["CSE", "ECE"],
      ba: ["Economics", "English", "History", "Psychology"],
      ma: ["Economics", "English", "Sociology"],
      pg: ["MBA", "MSc Physics", "MSc Maths"],
    },
    admission: [
      "SNUSAT or JEE Main / SAT",
      "Apply at admissions.snu.edu.in",
      "Liberal arts + tech combo",
      "400–500 BTech seats",
    ],
    highlights: ["Interdisciplinary", "Research-first", "Liberal arts + tech", "Growing placements"],
    topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "KPMG", "Deloitte"],
  },
  {
    id: 11,
    name: "KL University",
    fullName: "KL University",
    location: "Vijayawada, Andhra Pradesh",
    nirf: 41,
    naac: "A+",
    established: 1980,
    website: "https://www.kluniversity.in",
    applyLink: "https://www.kluniversity.in/admissions",
    entranceExam: "KLEEE / JEE Main",
    logo: "KLU",
    color: "#006400",
    fees: { btech: "1.5 – 2.5 L/yr", mtech: "1.2 – 2.0 L/yr" },
    avgPackage: "₹6.5 LPA",
    highestPackage: "₹38 LPA",
    courses: {
      btech: ["CSE", "IT", "ECE", "Mechanical", "Civil", "AI & ML"],
      mtech: ["CSE", "ECE", "Structural"],
      ba: ["English", "Economics", "Political Science"],
      ma: ["English", "Economics"],
      pg: ["MBA", "MCA", "MSc"],
    },
    admission: [
      "KLEEE or JEE Main",
      "Apply at kluniversity.in",
      "Affordable fees",
      "Innovation-focused",
    ],
    highlights: ["Innovation focus", "Affordable", "South India hub", "Entrepreneurship cell"],
    topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "Capgemini"],
  },
  {
    id: 12,
    name: "Bennett University",
    fullName: "Bennett University (Times Group)",
    location: "Greater Noida, UP",
    nirf: 72,
    naac: "A",
    established: 2016,
    website: "https://bennett.edu.in",
    applyLink: "https://bennett.edu.in/admissions",
    entranceExam: "JEE Main / BU GATE",
    logo: "BU",
    color: "#D32F2F",
    fees: { btech: "2.5 – 4.0 L/yr", mtech: "2.0 – 3.0 L/yr" },
    avgPackage: "₹7.8 LPA",
    highestPackage: "₹40 LPA",
    courses: {
      btech: ["CSE", "ECE", "Mechanical", "IT", "AI & ML"],
      mtech: ["CSE", "ECE"],
      ba: ["Journalism & Mass Comm", "Economics"],
      ma: ["Journalism", "Economics"],
      pg: ["MBA", "MCA", "MSc"],
    },
    admission: [
      "JEE Main score accepted",
      "Apply at bennett.edu.in",
      "Times Group backing",
      "Media + Tech advantage",
    ],
    highlights: ["Times Group backed", "Media advantage", "Industry mentors", "Modern campus"],
    topRecruiters: ["TCS", "Wipro", "Times Group", "Infosys", "HCL"],
  },
];

export const allCourseTypes = ["All", "BTech", "MTech", "BA", "MA", "PG"];
