export const exams = [
  // ── ENGINEERING ──
  {
    id: 1,
    name: "JEE Main",
    fullName: "Joint Entrance Examination – Main",
    category: "Engineering",
    conductedBy: "NTA (National Testing Agency)",
    level: "National",
    difficulty: "High",
    color: "#1a5276",
    badge: "JEE",
    stream: "PCM",
    admitsTo: ["NITs", "IIITs", "GFTIs", "Private Colleges"],
    courses: ["B.Tech", "B.E", "B.Arch", "B.Planning"],
    eligibility: ["Class 12 with PCM", "Min 75% marks (65% for SC/ST)", "No age limit"],
    pattern: ["2 Papers", "Paper 1: Maths + Physics + Chemistry", "300 marks", "2 sessions/year (Jan & Apr)", "CBT mode"],
    examDate: "January & April",
    applyLink: "https://jeemain.nta.ac.in",
    website: "https://jeemain.nta.ac.in",
    fee: "₹1000 (General) / ₹500 (SC/ST/PwD)",
    importantDates: { notification: "November", exam: "Jan & Apr", result: "Feb & May" },
    tips: ["Focus on NCERT first", "Solve previous 10 years papers", "Mock tests weekly", "Time management is key"],
    avgAttempts: "12+ Lakh students/year",
    careerScope: ["IIT via JEE Advanced", "NIT/IIIT admission", "Private college gateway"],
  },
  {
    id: 2,
    name: "JEE Advanced",
    fullName: "Joint Entrance Examination – Advanced",
    category: "Engineering",
    conductedBy: "IITs (rotational basis)",
    level: "National",
    difficulty: "Very High",
    color: "#1a3a5c",
    badge: "IIT",
    stream: "PCM",
    admitsTo: ["IIT Bombay", "IIT Delhi", "IIT Madras", "IIT Kanpur", "IIT Kharagpur", "23 IITs"],
    courses: ["B.Tech", "B.S", "Dual Degree"],
    eligibility: ["Top 2.5 Lakh JEE Main qualifiers", "Max 2 attempts", "Class 12 in 2024 or 2025"],
    pattern: ["2 Papers (Paper 1 + Paper 2)", "Both mandatory", "Physics + Chemistry + Maths", "MCQ + Integer type"],
    examDate: "May",
    applyLink: "https://jeeadv.ac.in",
    website: "https://jeeadv.ac.in",
    fee: "₹2800 (General) / ₹1400 (SC/ST/PwD/Female)",
    importantDates: { notification: "April", exam: "May", result: "June" },
    tips: ["Clear JEE Main first", "NCERT + HC Verma + Irodov", "Practice integer-type questions", "Manage Paper 1 & 2 strategy"],
    avgAttempts: "2.5 Lakh students/year",
    careerScope: ["IIT B.Tech", "Best tech jobs", "Global recognition", "Research at IITs"],
  },
  {
    id: 3,
    name: "BITSAT",
    fullName: "BITS Admission Test",
    category: "Engineering",
    conductedBy: "BITS Pilani",
    level: "University",
    difficulty: "High",
    color: "#6c1a1a",
    badge: "BITS",
    stream: "PCM",
    admitsTo: ["BITS Pilani", "BITS Goa", "BITS Hyderabad"],
    courses: ["B.E", "B.Pharm", "M.Sc Dual Degree"],
    eligibility: ["Class 12 PCM", "Min 75% in PCM", "English compulsory"],
    pattern: ["130 questions", "Physics + Chemistry + Maths + English + Logical", "3 hours", "Online CBT"],
    examDate: "May – June",
    applyLink: "https://www.bitsadmission.com",
    website: "https://www.bits-pilani.ac.in",
    fee: "₹2900 (1 session) / ₹5400 (both sessions)",
    importantDates: { notification: "January", exam: "May-June", result: "July" },
    tips: ["NCERT + HC Verma basics", "Speed is crucial — 130 Qs in 3 hrs", "Bonus questions strategy", "No JEE Main needed"],
    avgAttempts: "3+ Lakh students/year",
    careerScope: ["Top private engineering", "Strong alumni network", "No reservation seats"],
  },
  {
    id: 4,
    name: "VITEEE",
    fullName: "VIT Engineering Entrance Exam",
    category: "Engineering",
    conductedBy: "VIT University",
    level: "University",
    difficulty: "Moderate",
    color: "#145a32",
    badge: "VIT",
    stream: "PCM / PCB",
    admitsTo: ["VIT Vellore", "VIT Chennai", "VIT-AP", "VIT Bhopal"],
    courses: ["B.Tech"],
    eligibility: ["Class 12 PCM or PCB", "Min 60% in main subjects"],
    pattern: ["125 questions", "Physics + Chemistry + Maths/Bio + Aptitude + English", "2.5 hours", "Online CBT"],
    examDate: "April",
    applyLink: "https://applications.vit.ac.in",
    website: "https://vit.ac.in",
    fee: "₹1,350",
    importantDates: { notification: "November", exam: "April", result: "April-May" },
    tips: ["Easier than JEE", "Good backup for JEE aspirants", "Apply early for slot booking", "Focus on speed"],
    avgAttempts: "2+ Lakh students/year",
    careerScope: ["Top private engineering college", "6000+ seats", "Great placements"],
  },
  {
    id: 5,
    name: "SRMJEEE",
    fullName: "SRM Joint Engineering Entrance Exam",
    category: "Engineering",
    conductedBy: "SRM University",
    level: "University",
    difficulty: "Moderate",
    color: "#1a4a7a",
    badge: "SRM",
    stream: "PCM / PCB",
    admitsTo: ["SRM Kattankulathur", "SRM Ramapuram", "SRM NCR", "SRM Amaravati"],
    courses: ["B.Tech"],
    eligibility: ["Class 12 PCM or PCB", "Min 60% marks"],
    pattern: ["125 questions", "Physics + Chemistry + Maths/Bio", "2.5 hours"],
    examDate: "April – May",
    applyLink: "https://www.srmist.edu.in/admissions",
    website: "https://www.srmist.edu.in",
    fee: "₹1,100",
    importantDates: { notification: "October", exam: "April-May", result: "May" },
    tips: ["JEE Main accepted too", "Apply for multiple campuses", "Online counselling process"],
    avgAttempts: "1.5 Lakh+/year",
    careerScope: ["Multiple campus options", "7000+ seats", "Strong IT placements"],
  },
  {
    id: 6,
    name: "MHT-CET",
    fullName: "Maharashtra Common Entrance Test",
    category: "Engineering",
    conductedBy: "State CET Cell, Maharashtra",
    level: "State",
    difficulty: "Moderate",
    color: "#7d6608",
    badge: "MHT",
    stream: "PCM",
    admitsTo: ["All Maharashtra Engineering Colleges", "Govt + Private"],
    courses: ["B.Tech", "B.E", "B.Pharm"],
    eligibility: ["Class 12 PCM", "Maharashtra domicile preferred", "Min 50% PCM"],
    pattern: ["150 questions", "Physics + Chemistry + Maths", "3 hours", "MCQ based"],
    examDate: "April – May",
    applyLink: "https://cetcell.mahacet.org",
    website: "https://cetcell.mahacet.org",
    fee: "₹800",
    importantDates: { notification: "February", exam: "Apr-May", result: "June" },
    tips: ["Maharashtra state colleges", "Based on Class 11 & 12 Maha board syllabus", "Good for Pune/Mumbai colleges"],
    avgAttempts: "4+ Lakh/year",
    careerScope: ["Good state college options", "Cost-effective education", "Strong Maharashtra industry"],
  },

  // ── MEDICAL ──
  {
    id: 7,
    name: "NEET UG",
    fullName: "National Eligibility cum Entrance Test (UG)",
    category: "Medical",
    conductedBy: "NTA",
    level: "National",
    difficulty: "Very High",
    color: "#7b241c",
    badge: "NEET",
    stream: "PCB",
    admitsTo: ["AIIMS", "All Govt Medical Colleges", "Private Medical Colleges"],
    courses: ["MBBS", "BDS", "BAMS", "BHMS", "BVSc", "BSc Nursing"],
    eligibility: ["Class 12 PCB", "Min 50% (40% for SC/ST)", "Age 17+ years"],
    pattern: ["180 MCQs", "Physics (45) + Chemistry (45) + Biology (90)", "3 hours 20 min", "Offline OMR"],
    examDate: "May",
    applyLink: "https://neet.nta.nic.in",
    website: "https://neet.nta.nic.in",
    fee: "₹1700 (General) / ₹1000 (SC/ST)",
    importantDates: { notification: "February", exam: "May", result: "June" },
    tips: ["NCERT Biology is king", "20+ Lakh compete — start early", "Previous years are gold", "Biology = 360 marks, prioritize it"],
    avgAttempts: "20+ Lakh students/year",
    careerScope: ["MBBS → Doctor", "BDS → Dentist", "AYUSH → Alternative medicine"],
  },

  // ── LAW ──
  {
    id: 8,
    name: "CLAT",
    fullName: "Common Law Admission Test",
    category: "Law",
    conductedBy: "Consortium of NLUs",
    level: "National",
    difficulty: "High",
    color: "#4a235a",
    badge: "LAW",
    stream: "Any Stream",
    admitsTo: ["NLSIU Bangalore", "NALSAR Hyderabad", "NLU Delhi", "22 NLUs"],
    courses: ["BA LLB (5 yr)", "BBA LLB (5 yr)", "LLM"],
    eligibility: ["Class 12 any stream", "Min 45% marks (40% SC/ST)", "No age limit"],
    pattern: ["120 questions", "English + GK + Legal Reasoning + Logical + Maths", "2 hours", "CBT"],
    examDate: "December",
    applyLink: "https://consortiumofnlus.ac.in",
    website: "https://consortiumofnlus.ac.in",
    fee: "₹4,000",
    importantDates: { notification: "August", exam: "December", result: "January" },
    tips: ["Read newspapers daily", "Legal reasoning practice is key", "GK current affairs important", "Open to all streams"],
    avgAttempts: "75,000+/year",
    careerScope: ["Advocate", "Corporate lawyer", "Judge", "Legal consultant", "IAS via UPSC"],
  },
  {
    id: 9,
    name: "AILET",
    fullName: "All India Law Entrance Test",
    category: "Law",
    conductedBy: "NLU Delhi",
    level: "National",
    difficulty: "High",
    color: "#5b2c6f",
    badge: "NLU",
    stream: "Any Stream",
    admitsTo: ["NLU Delhi (only)"],
    courses: ["BA LLB", "LLM", "PhD Law"],
    eligibility: ["Class 12 any stream", "Min 50% marks", "No age limit"],
    pattern: ["150 questions", "English + GK + Legal Aptitude + Reasoning", "1.5 hours"],
    examDate: "December",
    applyLink: "https://nationallawuniversitydelhi.in",
    website: "https://nationallawuniversitydelhi.in",
    fee: "₹3,000",
    importantDates: { notification: "September", exam: "December", result: "January" },
    tips: ["Considered tougher than CLAT", "NLU Delhi is highly prestigious", "Legal GK focus"],
    avgAttempts: "40,000+/year",
    careerScope: ["NLU Delhi alumni — top law firms", "Supreme Court practice", "Judiciary"],
  },

  // ── MANAGEMENT ──
  {
    id: 10,
    name: "IPMAT",
    fullName: "Integrated Programme in Management Aptitude Test",
    category: "Management",
    conductedBy: "IIM Indore",
    level: "National",
    difficulty: "High",
    color: "#1e5945",
    badge: "IIM",
    stream: "Any Stream",
    admitsTo: ["IIM Indore", "IIM Ranchi", "IIM Rohtak", "IIFT Delhi"],
    courses: ["5-year Integrated MBA (IPM)"],
    eligibility: ["Class 12 any stream", "Min 60% in Class 10 & 12", "Age max 20 years"],
    pattern: ["Quantitative Ability + Verbal Ability", "MCQ + Short Answer", "120 minutes"],
    examDate: "May",
    applyLink: "https://iimcat.ac.in",
    website: "https://www.iimidr.ac.in",
    fee: "₹4,130",
    importantDates: { notification: "February", exam: "May", result: "June" },
    tips: ["Start after Class 11", "Maths + English focus", "IIM brand after 5 years", "Gateway to top B-schools"],
    avgAttempts: "30,000+/year",
    careerScope: ["IIM MBA without CAT", "Top consulting firms", "Startups", "Corporate leadership"],
  },

  // ── DESIGN ──
  {
    id: 11,
    name: "NIFT Entrance",
    fullName: "National Institute of Fashion Technology Entrance",
    category: "Design",
    conductedBy: "NIFT",
    level: "National",
    difficulty: "Moderate",
    color: "#884ea0",
    badge: "NIFT",
    stream: "Any Stream",
    admitsTo: ["NIFT Delhi", "NIFT Mumbai", "NIFT 18 campuses"],
    courses: ["B.Des (Fashion Design)", "B.FTech", "B.Des (Knitwear)", "B.Des (Textile)"],
    eligibility: ["Class 12 any stream", "Min 45% marks", "Creative aptitude required"],
    pattern: ["CAT paper + GAT paper", "Creative Ability Test + General Ability Test", "Situation Test for shortlisted"],
    examDate: "February",
    applyLink: "https://admissions.nift.ac.in",
    website: "https://nift.ac.in",
    fee: "₹2,500",
    importantDates: { notification: "November", exam: "February", result: "April" },
    tips: ["Practice sketching daily", "CAT is creative — practice portfolio", "No Maths required", "Open to all streams"],
    avgAttempts: "70,000+/year",
    careerScope: ["Fashion designer", "Textile designer", "Stylist", "Brand consultant"],
  },
  {
    id: 12,
    name: "NID DAT",
    fullName: "National Institute of Design Design Aptitude Test",
    category: "Design",
    conductedBy: "NID",
    level: "National",
    difficulty: "Moderate",
    color: "#7d4e24",
    badge: "NID",
    stream: "Any Stream",
    admitsTo: ["NID Ahmedabad", "NID Bangalore", "NID 5 campuses"],
    courses: ["B.Des (Industrial)", "B.Des (Communication)", "B.Des (Textile & Apparel)"],
    eligibility: ["Class 12 any stream", "No minimum % barrier", "Creative portfolio helps"],
    pattern: ["Prelims + Mains", "Drawing + Creative writing + 3D thinking", "Studio test"],
    examDate: "January",
    applyLink: "https://admissions.nid.edu",
    website: "https://www.nid.edu",
    fee: "₹2,000",
    importantDates: { notification: "September", exam: "January", result: "March" },
    tips: ["Observation & creativity is tested", "Practice product sketches", "No Maths needed", "Think like a designer"],
    avgAttempts: "25,000+/year",
    careerScope: ["Product designer", "UI/UX designer", "Industrial designer", "Animation"],
  },

  // ── DEFENCE ──
  {
    id: 13,
    name: "NDA",
    fullName: "National Defence Academy Exam",
    category: "Defence",
    conductedBy: "UPSC",
    level: "National",
    difficulty: "High",
    color: "#2e4057",
    badge: "NDA",
    stream: "PCM (Army/Navy/Air Force)",
    admitsTo: ["NDA Pune", "Indian Military Academy", "Naval Academy", "Air Force Academy"],
    courses: ["B.Tech (Army/Navy/AF)", "3-year NDA training"],
    eligibility: ["Class 12 PCM (for Navy/AF)", "Any stream for Army", "Age 16.5 – 19.5 years", "Unmarried males only"],
    pattern: ["Paper 1: Maths (300 marks)", "Paper 2: GAT (600 marks)", "SSB Interview (900 marks)", "Total 1800 marks"],
    examDate: "April & September",
    applyLink: "https://upsconline.nic.in",
    website: "https://upsc.gov.in",
    fee: "₹100 (Free for SC/ST/Female)",
    importantDates: { notification: "December & June", exam: "Apr & Sep", result: "After SSB" },
    tips: ["Physical fitness equally important", "Maths + English focus", "SSB interview is the real challenge", "Start in Class 11"],
    avgAttempts: "4+ Lakh/year",
    careerScope: ["Indian Army Officer", "Navy Officer", "Air Force Pilot", "Government pension + prestige"],
  },

  // ── GENERAL / CENTRAL UNIVERSITIES ──
  {
    id: 14,
    name: "CUET UG",
    fullName: "Common University Entrance Test (UG)",
    category: "Central Universities",
    conductedBy: "NTA",
    level: "National",
    difficulty: "Moderate",
    color: "#1a6b3c",
    badge: "CUET",
    stream: "Any Stream",
    admitsTo: ["Delhi University", "BHU", "JNU", "45+ Central Universities", "Many state & private universities"],
    courses: ["BA", "BSc", "BCom", "BBA", "BCA", "All UG programs"],
    eligibility: ["Class 12 any stream", "No minimum % set by NTA (colleges set cutoffs)", "All streams eligible"],
    pattern: ["Section IA/IB: Languages", "Section II: Domain subjects", "Section III: General Test", "CBT mode"],
    examDate: "May – June",
    applyLink: "https://cuet.samarth.ac.in",
    website: "https://cuet.nta.nic.in",
    fee: "₹650 (3 subjects) / ₹750 (4-6 subjects)",
    importantDates: { notification: "February", exam: "May-June", result: "July" },
    tips: ["DU aspirants must appear", "Choose domain subjects wisely", "General Test for most BBA/BSc programs", "Replaces DU/BHU direct admission"],
    avgAttempts: "15+ Lakh/year",
    careerScope: ["DU, BHU, JNU admission", "BA/BCom/BSc at top central universities", "Widest scope exam"],
  },
];

export const categories = ["All", "Engineering", "Medical", "Law", "Management", "Design", "Defence", "Central Universities"];
export const difficulties = ["All", "Moderate", "High", "Very High"];
