// ─── ALL TOOLS DATA ────────────────────────────────────────────────────────────
export const tools = [
  // ── PREDICTORS ──
  {
    id: 1,
    name: "JEE Main Percentile Predictor",
    description: "Enter your marks → get estimated percentile & AIR rank instantly",
    icon: "📊",
    category: "Predictor",
    tag: "Most Used",
    tagColor: "bg-green-100 text-green-700",
    color: "border-blue-200 hover:border-blue-400",
    iconBg: "bg-blue-50",
    tool: "jee-percentile",
  },
  {
    id: 2,
    name: "NEET Rank Predictor",
    description: "Convert your NEET score to expected All India Rank & college list",
    icon: "🏥",
    category: "Predictor",
    tag: "Popular",
    tagColor: "bg-red-100 text-red-700",
    color: "border-red-200 hover:border-red-400",
    iconBg: "bg-red-50",
    tool: "neet-rank",
  },
  {
    id: 3,
    name: "College Cutoff Checker",
    description: "Check last year cutoffs for any college + branch + category",
    icon: "🎯",
    category: "Predictor",
    tag: "New",
    tagColor: "bg-purple-100 text-purple-700",
    color: "border-purple-200 hover:border-purple-400",
    iconBg: "bg-purple-50",
    tool: "cutoff-checker",
  },
  {
    id: 4,
    name: "JEE Marks vs Rank",
    description: "See what rank your JEE marks will fetch — shift & category wise",
    icon: "📈",
    category: "Predictor",
    tag: "Useful",
    tagColor: "bg-yellow-100 text-yellow-700",
    color: "border-yellow-200 hover:border-yellow-400",
    iconBg: "bg-yellow-50",
    tool: "marks-rank",
  },

  // ── CALCULATORS ──
  {
    id: 5,
    name: "EMI / Fee Calculator",
    description: "Plan your education loan — monthly EMI based on fees & duration",
    icon: "💰",
    category: "Calculator",
    tag: "Finance",
    tagColor: "bg-green-100 text-green-700",
    color: "border-green-200 hover:border-green-400",
    iconBg: "bg-green-50",
    tool: "emi-calc",
  },
  {
    id: 6,
    name: "CGPA to Percentage",
    description: "Convert CGPA → Percentage instantly (CBSE, VTU, Mumbai Univ formula)",
    icon: "🔢",
    category: "Calculator",
    tag: "Quick",
    tagColor: "bg-blue-100 text-blue-700",
    color: "border-blue-200 hover:border-blue-400",
    iconBg: "bg-blue-50",
    tool: "cgpa-calc",
  },
  {
    id: 7,
    name: "Scholarship Calculator",
    description: "Check if you qualify for merit scholarships based on marks & income",
    icon: "🎓",
    category: "Calculator",
    tag: "Savings",
    tagColor: "bg-orange-100 text-orange-700",
    color: "border-orange-200 hover:border-orange-400",
    iconBg: "bg-orange-50",
    tool: "scholarship-calc",
  },

  // ── TRACKERS ──
  {
    id: 8,
    name: "Exam Countdown Timer",
    description: "Days left for JEE, NEET, CUET, CLAT & more — all in one place",
    icon: "⏳",
    category: "Tracker",
    tag: "Live",
    tagColor: "bg-red-100 text-red-700",
    color: "border-red-200 hover:border-red-400",
    iconBg: "bg-red-50",
    tool: "countdown",
  },
  {
    id: 9,
    name: "Application Tracker",
    description: "Track your college applications — Applied, Pending, Result status",
    icon: "📋",
    category: "Tracker",
    tag: "Organize",
    tagColor: "bg-indigo-100 text-indigo-700",
    color: "border-indigo-200 hover:border-indigo-400",
    iconBg: "bg-indigo-50",
    tool: "app-tracker",
  },
  {
    id: 10,
    name: "Study Planner",
    description: "Create your exam study schedule — days, subjects, hours tracker",
    icon: "📅",
    category: "Tracker",
    tag: "Productivity",
    tagColor: "bg-teal-100 text-teal-700",
    color: "border-teal-200 hover:border-teal-400",
    iconBg: "bg-teal-50",
    tool: "study-plan",
  },

  // ── GUIDES ──
  {
    id: 11,
    name: "Career Path Finder",
    description: "Answer 5 questions → get best career + stream + college recommendations",
    icon: "🧭",
    category: "Guide",
    tag: "AI Powered",
    tagColor: "bg-brand-100 text-brand-700",
    color: "border-green-200 hover:border-green-400",
    iconBg: "bg-green-50",
    tool: "career-finder",
  },
  {
    id: 12,
    name: "Stream Selector",
    description: "Science / Commerce / Arts — which stream suits you best after 10th?",
    icon: "🔍",
    category: "Guide",
    tag: "Interactive",
    tagColor: "bg-pink-100 text-pink-700",
    color: "border-pink-200 hover:border-pink-400",
    iconBg: "bg-pink-50",
    tool: "stream-selector",
  },
];

export const categories = ["All", "Predictor", "Calculator", "Tracker", "Guide"];
